### ISSUE TITLE
Fix tablet_ui flow problems

### ISSUE THREAD

**Issue by pisuke** [LUSHDigital/lrpi_tablet_ui#36]
1. UI crashes when there is no srt file
2. UI crashes when end of file (spinning wheel)
3. UI crashes when loading big file and next or previous track is pressed
4. UI crashes when loading big file and clicking on back arrow to go to main menu

**Comment by InBrewJ** [comment]
https://sentry.io/organizations/arupiot/issues/1145017653/?project=1391137&query=is%3Aunresolved

**Comment by InBrewJ** [comment]
1>

```
[2019-08-09 18:11:52,628] ERROR in app: Exception on /crossfade [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "Server.py", line 272, in get
    response = player.fadeDown(pathToTrack, int(args["interval"]),  subs, BUILT_PATH + srtFileName)
  File "/opt/code/flask/Player.py", line 177, in fadeDown
    self.lighting.exit()
  File "/opt/code/flask/Lighting.py", line 518, in exit
    self.__del__()
  File "/opt/code/flask/Lighting.py", line 527, in __del__
    self.scheduler.shutdown()
  File "/usr/local/lib/python3.5/dist-packages/apscheduler/schedulers/background.py", line 39, in shutdown
    super(BackgroundScheduler, self).shutdown(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/apscheduler/schedulers/blocking.py", line 22, in shutdown
    super(BlockingScheduler, self).shutdown(wait)
  File "/usr/local/lib/python3.5/dist-packages/apscheduler/schedulers/base.py", line 180, in shutdown
    raise SchedulerNotRunningError
apscheduler.schedulers.SchedulerNotRunningError: Scheduler is not running
10.9.4.30 - - [09/Aug/2019 18:11:52] "GET /crossfade?id=98f0cb1c6476a082d67598614c7bb2cf&interval=4 HTTP/1.1" 500 -
```

It's to do with calling (what I presume to be) a destructor on the scheduler that doesn't exist. Should be a simple fix

**Comment by InBrewJ** [comment]
With large srts, skipping tracks results in the following (presumably from the scheduler:)

```
Execution of job "LushRoomsLighting.tick (trigger: interval[0:00:00.100000], next run at: 2019-08-09 20:44:25 UTC)" skipped: maximum number of running instances reached (16)
```

**Comment by pisuke** [comment]
Yes, I'm aware, the scheduler has limitations and drops some frames if it doesn't manage to process the frame to keep timing. I've tried many settings back in February when instancing it and the ones in the current code are the best settings I can come up with.

**Comment by InBrewJ** [comment]
For 3>

- Could pause the scheduler before sending the command to omxplayer to load the new track
- Pausing seems to work fine with the current scheduler settings
